### ISSUE TITLE
Mcp X LibreChat

### ISSUE THREAD

**Issue by Tmegaa** [galaxyproject/galaxy-mcp#2]
### **Question/improvement** 

I was wondering if it is possible to connect the Galaxy MCP to LibreChat ?

I feel like it could be possible but I'm not sure how to do so. Basically  I would have add some lines in my .yaml file like this : 

_Exemple with a supabase map using postgres_
```
supabase:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-postgres"
      - postgresql://postgres:postgres@127.0.0.1:54322/postgres
``` 

Is it possible yet ? And if not, I think that it may be a great feature that will improve the ease to install.
